name: Lunes Auto Login(Sweet-Node6-US)

on:
  workflow_dispatch:
 # schedule:
    #- cron: "0 23 * * *"

jobs:
  login:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install
        run: |
          # 强制安装依赖，不管有没有 lock 文件
          npm install
          # 安装 Playwright 浏览器及其系统依赖
          npx playwright install --with-deps chromium

      - name: Run
        env:
          LUNES_USERNAME: ${{ secrets.LUNES_USERNAME }}
          LUNES_PASSWORD: ${{ secrets.LUNES_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          node scripts/login.js

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "*.png"
          if-no-files-found: ignore
